### ISSUE TITLE
Please implement a test flag that uses self-signed certs

### ISSUE THREAD

**Issue by SegHaxx** [snikket-im/snikket-web-portal#129]
Hi I am trying to evaluate Snikket for use, so I wish to deploy it on an internal network for testing. But if i do this, it hangs forever trying to get certs from letsencrypt.

There needs to be a test flag in the config, that generates self-signed certificates and does not interact with letsencrypt.

Other containers I've used support this.

**Comment by mwild1** [comment]
Hi, thanks for the request!

Unfortunately deploying Snikket on an internal network is tricky to do for various reasons, and it wouldn't be fully functional even if certificates could be obtained. For example, support for push notifications requires the Snikket instance to be publicly accessible, and file sharing requires an extra domain which is typically not going to be available on an internal network.

So although I understand the use-case, I think it's too complex to do it properly. I am working on something along these lines for a "developer mode" functionality, but it's quite fragile and I'm not yet satisfied enough to make it official functionality any time soon.

I hope this helps explain the problems with fulfilling this request. I'm going to close the issue, as otherwise the "we might do this one day" issues tend to accumulate and make it hard to find things we are actively trying to focus on.
