### ISSUE TITLE
Web login: "The CSRF tokens do not match"

### ISSUE THREAD

**Issue by clandestine-avocado** [snikket-im/snikket-web-portal#139]
When I attempt to log in via the web (vice on mobile) I get the error "Invalid input. The CSRF tokens do not match."

How would I rectify the certs?

**Comment by mwild1** [comment]
Hi, apologies we missed this issue. Rather than our issue tracker, the best place for support is our community channel: https://snikket.org/contact/

In any case, the error message you quoted is unrelated to certificates. It should clear itself if you reload the page. If not, check whether your browser might be blocking cookies. The web interface uses cookies to secure your session.
