### ISSUE TITLE
Add an F-Droid button on invite page

### ISSUE THREAD

**Issue by licaon-kter** [snikket-im/snikket-web-portal#52]
Around here I guess: https://github.com/snikket-im/snikket-web-portal/blob/1c4fa92c974da1b50a781b1b04d7362612b2182b/snikket_web/templates/invite_view.html#L27

**Comment by horazont** [comment]
@mwild1 Do we want to do this before https://gitlab.com/fdroid/fdroidclient/-/issues/1932 is resolved?

**Comment by mwild1** [comment]
Since we have no idea when that feature may be implemented in F-Droid (if ever), I don't think we can plan on waiting for it.

I think that the Play Store button should remain the primary CTA for Android users, but needs to be a link somewhere visible nearby (e.g. underneath) that links to F-Droid as an alternative.

Both F-Droid and iOS both currently suffer from the "user needs to revisit the invite after app installation" problem, and I'm still thinking about if there is anything we can do to improve this (some additional text, or an intermediate page that just contains the XMPP URI button and says "come back here after you've installed the app").

**Comment by licaon-kter** [comment]
@horazont 
The rule is _"never hold your breath waiting for F-Droid"_ :)

**Comment by horazont** [comment]
Ok, then I suggest that we add this to the 0.2.0 milestone and also create a separate issue for iOS.

**Comment by mwild1** [comment]
wfm

**Comment by horazont** [comment]
@licaon-kter What is the appropriate way to link to an f-droid app from a webpage? I was unable to find anything. As a first measure, I’ll link to the app web page on f-droid, but that does not seem user friendly. It would be nicer if I could somehow make f-droid open automatically if its installed. Do you happen to know how that could work?

**Comment by horazont** [comment]
Also, is there any artwork which could be used for an "Install from F-droid" button?

**Comment by licaon-kter** [comment]
`<a href="https://f-droid.org/app/appid"><img src="https://f-droid.org/badge/get-it-on.png" alt="Get it on F-Droid" height="100"></a>`

The old `market:...` schema is not working anymore?

**Comment by horazont** [comment]
Market works, thanks!

**Comment by mwild1** [comment]
I had warning from someone (Georg?) that `market:` is unfortunately also intercepted by some proprietary app stores, e.g. Samsung's, on some devices. I'm guessing if we only use it for an explicit F-Droid link though, a user with F-Droid will not have this problem.

**Comment by horazont** [comment]
Right if we find that there’s an issue to solve there, we can still fix it.
