### ISSUE TITLE
Snikket Android is confused when the HTTPS QR code instead of the XMPP QR code is scanned

### ISSUE THREAD

**Issue by horazont** [snikket-im/snikket-web-portal#56]
### Steps to reproduce

1. Open an invite in the broswer
2. Tap the "not on mobile?" button
3. Scan QR code with Snikket Android

### What happened

It wants to add some contact to an existing account.

### What should happen instead

It should register using the invitation.

### Additional information

I think this should be improved in some way, because this might be the first instinct a user has (while other users may have the first instinct to scan the QR code with a dedicated scanner and open it in a browser, so we need something which works for both).

I would suggest to maybe add the XMPP URI to the HTTPS URL as anchor or something so that it can be extracted by the apps when they are faced with the HTTPS QR code.

Any reasons against that?

**Comment by mwild1** [comment]
Generally the goal is to minimize the amount of data in the QR code, which is why mod_invites_page injects the URI into a HTTP header and `<link>` tag instead. The more data in a QR code, the less easy it is to read. We don't have much control over the username/domain, but we would be putting the domain into the QR code twice :/

Daniel and I did briefly discuss discovery based on headers before now, and I think that's the best way to go (I also don't like parsing arbitrary URLs to extract anything that could hopefully be an XMPP URI).

**Comment by horazont** [comment]
Header and link is even better, although it requires the app to fetch the URL. But *I* am fine with that.

Do we have a "standard" header / link to use?

**Comment by mwild1** [comment]
In HTML:

```
<link rel="alternate" href="xmpp:foo@example.com?...">
```

In HTTP:

```
Link: <xmpp:foo@example.com?...>; rel="alternate"
```

Note that the URI must be surrounded the literals `<` and `>` in the Link header, per standards.

**Comment by horazont** [comment]
Perfect, that’s easy enough to do.
