### ISSUE TITLE
Add an error/message when cookies are blocked when trying to connect

### ISSUE THREAD

**Issue by GodGoldfish** [snikket-im/snikket-web-portal#82]
Hi, 
Snikket Web Portal doesn't show any message if the cookies are blocked so maybe it would be cool in some cases that it shows a message like "You need to allow the Snikket Web Portal to use cookies"

---

how to reproduce : 
delete and block your cookies of the snikket web portal
try to connect to a snikket web portal

**Comment by horazont** [comment]
The thing is, you can’t really distinguish a user who hasn’t accepted cookies from a user who just opened the portal in a fresh browser.

One way would be to have a redirection step which checks for a set cookie, but that has terrible user experience: a user who rejects cookies will then be sent in a redirect loop instead of an error message.

Which specific error did you get? Maybe we can change that error message to include a hint about cookies.

**Comment by GodGoldfish** [comment]
@horazont as i said there is no message so no error message, so if some people doesn't allow the cookies they will not be able to understand what's happening.

**Comment by mwild1** [comment]
I don't see any easy fix for this, nor have I seen others reporting the same problem. Pretty much no website will support login if you have first-party cookies blocked. Anybody who blocks first-party cookies will encounter this issue across the web, it's not really a Snikket problem.

So unless someone can identify a reasonable implementation that would improve the UX, I think we can close this issue. Thanks for reporting it nevertheless, sorry there isn't much we can do about it!
